rancher/python-agent

cattle/plugins/host-api/host_api.py

Added the new parameters for turning on jwt validation for host-api

Issue-141: Turn on jwt validation for host-api

---

cattle/plugins/docker/network/ipsec_tunnel.py
tests/docker/instance_activate_ipsec_lb_agent
tests/docker/instance_activate_ipsec_lb_agent_resp
tests/docker/instance_activate_ipsec_network_agent
tests/docker/instance_activate_ipsec_network_agent_resp
tests/test_docker.py

@ibuildthecloud Darren, ping me if you need more tests to be added for the fix.

Do ipSec tunnel support for NetworkAgent instance only

---

cattle/plugins/host_info/cpu.py

Fixes the cadvisor errors during startup.

Putting up more defenses around cadvisor not being available

---

cattle/plugins/docker/storage.py
tests/test_docker.py

Fixes tests for authed pulls.
References fixed for cattle patch.

Fix issue 164

---

cattle/__init__.py
cattle/compute/__init__.py
cattle/plugins/docker/__init__.py
cattle/plugins/docker/compute.py

This should still be backwards compatible with the current cattle (without my new changes).
Originally, I was hoping to submit my cattle PR some time tomorrow, but will likely be late Monday since I'll be busy reviewing James's PR.

First pass at SSL support for clusters

---

cattle/plugins/docker/compute.py

Addresses a bug where host-api would attempt to unmarshall the
container json before it was fully written.

Make container state file write atomic

---

cattle/plugins/volmgr/handler.py
cattle/plugins/volmgr/service.py
cattle/plugins/volmgr/volmgr.py
tests/test_docker_volmgr.py

Require volmgr v0.1.5, as in https://github.com/rancherio/cattle/pull/400 .

snapshot: idempotency support

---

cattle/plugins/docker/compute.py
tests/docker/instance_activate_labels
tests/docker/instance_activate_labels_resp
tests/test_docker.py

Corresponding cattle PR: https://github.com/rancherio/cattle/pull/415

Support for container.labels field

---

cattle/plugins/volmgr/handler.py
cattle/plugins/volmgr/volmgr.py
tests/test_docker_volmgr.py

Only cleanup other snapshots when it's already backed up and not the last one
Also cleanup some leftovers.

snapshot: Only keep last snapshot in internal snapshots

---

cattle/plugins/docker/compute.py
requirements.txt
tests/test_docker.py

workingDir
securityOpt
logConfig
pidMode
extraHosts
readOnly

Add more fields

---

cattle/__init__.py
cattle/plugins/docker/compute.py
tests/docker/ping_resp
tests/docker/ping_stat_exception_resp

pass along host labels via env variables

---

cattle/plugins/docker/compute.py
tests/test_docker.py

Resolves https://github.com/rancherio/cattle/issues/615
Checks for 'Created' status in ping logic to accomodate docker 1.7

404 on remove and 'Create' status bugs

---

cattle/plugins/docker/network.py
tests/test_docker.py

Addresses
rancherio/rancher#1221
rancherio/rancher#1225

Check for none on Ports and Env

---

tests/test_docker.py

Addresses https://github.com/rancher/rancher/issues/1518

Specify tag on test_ping

---

cattle/plugins/docker/network.py
tests/test_docker.py

and net=container.
https://github.com/rancher/rancher/issues/1562
@ibuildthecloud

Don't propagate links to docker when net=host is set

---

cattle/plugins/docker/compute.py
cattle/plugins/docker/network.py
tests/docker/instance_activate_bridge
tests/docker/instance_activate_bridge_resp
tests/test_docker_network.py

https://github.com/rancher/rancher/issues/1847

Bind public ports when network mode is bridge

---

cattle/plugins/docker/compute.py
tests/test_docker.py

https://github.com/rancher/rancher-compose/issues/54

Fix broken logConfig parameter

---

cattle/plugins/docker/delegate.py

https://github.com/rancher/rancher/issues/835

Wait a bit for config.update to appear if missing

---

cattle/plugins/docker/storage.py

If the pull status has neither status or error an error would be thrown.

Don't fail if pull status missing status and error key

---

cattle/plugins/host_info/cpu.py
tests/test_host_info_plugin.py

Merge to resolve an issue where the currently running clock speed is shown instead of the CPU's 'normal' speed. https://github.com/rancher/rancher/issues/2365

CPU Speed Reporting Fix

---

cattle/plugins/docker/compute.py
tests/test_docker.py

bypass volume-driver validation

---

cattle/plugins/docker/storage.py
tests/test_docker.py

Addresses rancher/rancher#2791

Tolerate empty driver_opts in volume create

---

requirements.txt
tests/test_docker_images.py

Update requirements. Add  case.

---

cattle/plugins/docker/storage.py
scripts/test
scripts/warm
tests/test_docker.py

Also speed up the ping test so it waits a lot less and don't assert
memoryswap if it isn't supported on the current host.

Convert driver_opts to dict if JsonObject

---

cattle/plugins/docker/compute.py
tests/docker/ping_resp
tests/docker/ping_stat_exception_resp

https://github.com/rancher/rancher/issues/3149

Pass host labels to be applied on start and update in seperate fields

---

cattle/plugins/docker/compute.py
tests/docker_common.py
tests/test_docker.py

Fixes two bugs:
1. Exception that occurs if no name is set on the instance
2. Incorrectly checking to see if name is already in use by another
container

Fix container naming bugs

---

cattle/agent/handler.py
cattle/plugins/docker/storage.py
cattle/plugins/docker/util.py

This reverts commit 80001ccfe3beace65c1874c01278bffdb7b30de9.

Revert "Dont delete volumes when deleting container"

---

cattle/plugins/docker/__init__.py
cattle/plugins/docker/compute.py

I couldn't figure out a good way to write a test for this. So....no tests, wweeeeeeeeeeee!

Timeout on instance pings

---

cattle/plugins/docker/compute.py
cattle/plugins/docker/network.py
tests/test_docker_network.py

Addresses https://github.com/rancher/rancher/issues/3492

Allow hostname to be set when net is none

---

cattle/plugins/docker/compute.py
tests/docker/instance_activate_agent_instance_resp
tests/docker/instance_activate_bridge_resp
tests/docker/instance_activate_command_args_resp
tests/docker/instance_activate_command_null_resp
tests/docker/instance_activate_command_resp
tests/docker/instance_activate_double_links_resp
tests/docker/instance_activate_fields_resp
tests/docker/instance_activate_ipsec_lb_agent_resp
tests/docker/instance_activate_ipsec_network_agent_resp
tests/docker/instance_activate_ipsec_resp
tests/docker/instance_activate_labels_resp
tests/docker/instance_activate_links_no_service_resp
tests/docker/instance_activate_links_resp
tests/docker/instance_activate_ports
tests/docker/instance_activate_ports_resp
tests/docker/instance_activate_pull_resp
tests/docker/instance_activate_resp
tests/docker/instance_activate_volumes_resp
tests/docker/instance_deactivate_resp
tests/docker/native_container_activate_resp
tests/docker/native_container_deactivate_resp
tests/docker/native_container_not_running_resp
tests/docker_common.py
tests/test_docker.py
tests/test_docker_native.py

Also support binding same container port to more than one host port

Support binding to specific IP

---

cattle/plugins/docker/compute.py

if only rancher generated domains are provided; and only for non-system containers.
https://github.com/rancher/rancher/issues/4300
@ibuildthecloud just one concern - if the domain on host changes after the container's initial launch, even on container restart host resolv.conf changes won't be picked up (unlike it's done natively by docker when searchDomains param is null) because a) searchDomain param can't be modified on start b) as we read /etc/resolv.conf from rancher-agent container, and to get host's changes, this container would have to be restarted as well. Not sure how common this use case is.

Prepend hosts search domains to SearchDomain param

---

cattle/plugins/docker/compute.py

https://github.com/rancher/rancher/issues/4940
@cjellick

handle dnsSearch being None
