cattle/__init__.py, tests/test_config.py
Beyond the unit test, the more interesting question is how this impacts the loading of environment variables.
The obvious risk would be that some piece of code is dependent upon some particular environment variable being set explicitly to blank to convey something meaningful. It would be a futile effort to track down and test all those potential touch points. Here's what I've done to mitigate:
* Reviewed all the calls default_value to see if any of the would reasonably want a blank value
* Ran the whole suite tests in python-agent
* Ran the test_docker.py in the integration tests in cattle
* Manually tested against my go-machine-service changes that may eventually pass in a blank environment variable to ensure that the blank is handled correctly in that context (interpreted as being …
=> Treat blank env vars as unset

README.md
Docker tests are on by default. Can remove this setting from the readme.
=> Remove DOCKER_TEST from README.md

cattle/plugins/docker/__init__.py, cattle/plugins/docker/delegate.py, cattle/utils.py
Previously we would make a HTTP call to enter the container to run scripts.
Now that the python-agent can run in the PID namespace of the host we are
now able to just directly enter the namespace using nsenter.  "docker exec"
is not used because there is issues with properly handling input/output, for
example flushing and closing the input stream.
=> Use nsenter to process events in the agent-instance

cattle/agent/event.py, requirements.txt
psutil was only included to support non-Linux systems.  We are only
focusing on Linux so this will simplify things.
=> Remove psutil

dist-requirements.txt, requirements.txt, scripts/bootstrap, scripts/build, test-requirements.txt, tox.ini
The requirements files were starting to require dual entry, and
for sure, the requirements.txt file was not being used. This project
currently relies on the dist-requirements.txt for installation. This
pull update makes it so that top-level dependencies are added in
dist-requirements.txt and testing tools are added to
test-requirements.txt.
argparse is not included in the new dist-requirments because it is part of python 2.7 stdlib.
=> Cleaned up requirements

cattle/agent/handler.py, cattle/compute/__init__.py
Containers can legitmately go to stopped right after starting, so the
instance_activate method should not check that it they're running after
executing the docker command.
=> Don't check that containers are running in activate

cattle/plugins/host_info/memory.py, cattle/plugins/host_info/os_c.py, cattle/utils.py, tests/test_host_info_plugin.py
Tests were not running on a Mac directly. Turns out the errors from
cAdvisor client were causing incorrect results up the stack. I refactored the cAdvisor client code to be more resilient, and to return more sane values.
=> Set the Linux context for Linux tests.

.drone.yml, Dockerfile, tests/docker/image_activate_resp, tests/docker/instance_activate_agent_instance_resp, tests/docker/instance_activate_command_args_resp, tests/docker/instance_activate_command_null_resp, tests/docker/instance_activate_command_resp, tests/docker/instance_activate_fields_resp, tests/docker/instance_activate_ipsec_lb_agent_resp, tests/docker/instance_activate_ipsec_network_agent_resp, tests/docker/instance_activate_ipsec_resp, tests/docker/instance_activate_links_no_service_resp, tests/docker/instance_activate_links_resp, tests/docker/instance_activate_native_container_not_running_resp, tests/docker/instance_activate_native_container_resp, tests/docker/instance_activate_ports_resp, tests/docker/instance_activate_resp, tests/docker/instance_activate_volumes_resp, tests/docker/instance_deactivate_native_container_resp, tests/docker/instance_deactivate_resp
I also notice that the response for image_activate of "Label" is none, rather than {} in other cases. Probably a bug in docker side.
=> tests: update response for Docker 1.6

cattle/plugins/docker/compute.py, tests/docker/instance_activate_native_container, tests/docker/instance_activate_native_container_not_running, tests/docker/instance_activate_volumes, tests/docker/instance_deactivate_native_container
If an agent is deleted and re-added, it doesn't get recognized
successfully by catttle. This is due to how we are looking the
container up. This fixes how we look up containers to prefer uuid over
external id.
=> Fix agent delete issue

cattle/plugins/docker/compute.py, tests/docker/ping_resp, tests/docker/ping_stat_exception_resp, tests/test_docker.py
Don't send containers that have been created but not started.
Change logic explicitly look for running containers and assume all
other containers are stopped (as opposed to explicitly looking for
stopped and assuming everything else is running, which is how the
previous logic worked).
=> Refactor instance ping logic

requirements.txt, scripts/bootstrap, scripts/build
Agents connecting to SSL servers were unable to connect to the  server because of the way urllib3 handled connections. Adding these libraries brings the libraries up to a good working state. 
Will be submitting rancher/agent PR to make sure the libraries are in the container.
=> Added Libraries to handle SSL

cattle/plugins/docker/storage.py
This flag can always be set to true because we want to ignore the checks for valid ssl on a registry with the docker-py client. Let docker decide if we can pull.
=> Pass insecure-registry=true to pull.

cattle/plugins/docker/compute.py, cattle/plugins/host_info/main.py, cattle/plugins/host_info/os_c.py, tests/test_host_info_plugin.py
Instead of getting the docker version from the client, we are now
using docker py to query the server for the host version of Docker.
In order to avoid circular imports a docker_client is now passed to
the OSCollector class.
Addresses rancherio/rancher#912
=> Fixed incorrect docker version from agent

cattle/plugins/docker/compute.py, tests/test_docker.py
Partially addresses https://github.com/rancherio/rancher/issues/1147
wherein one of the issues was that python agent would error out if a
container had the Labels field set to None.
This can happen if you start a container using an older version of
Docker and then upgrade.
=> Dont assume Labels field present

cattle/plugins/docker/compute.py, tests/docker/ping_resp, tests/test_docker.py
Docker 1.8 does not return image labels as part of a container's
inspect, update logic to look at image labels in addtion to container
labels when determining if a container is a system container.
=> Check image labels for system container

cattle/plugins/docker/compute.py, tests/test_docker.py
Query docker on startup for images with the io.rancher.container.system
label and cache them so that ping logic can use them to determine if a
contianer is a system container.
This functionality is already tested under test_docker.py/test_ping
=> Support custom rancher images for air gap

cattle/plugins/docker/compute.py, tests/docker/ping_resp, tests/test_docker.py
To identify system containers, we look for images containing our system label and we add those images to a cache that can be used on every 5 second ping where we report images.
This had a bug where in a container would say its image was 'rancher/agent' but the image reported by docker when list images was 'rancher/agent:latest'
To fix, when building the image cache, we'll rop ':latest' so that both 'rancher/agent:latest' and 'rancher/agent' are in the name cache.
=> When system image name cache, alias latest

cattle/plugins/host_info/disk.py, cattle/plugins/host_info/main.py, tests/host_info/cadvisor_machine, tests/test_host_info_plugin.py
This PR adds support to filter out device mapper pools from the filesystems key returned to the UI. By default cAdvisor returned the device mapper pool, which reported virtual space. The UI added the drive space up and displayed numbers with far more storage available then is really there. Several users have complained about this issue. 
Also, added in this is two new keys under diskInfo.
The first is dockerStorageDriver which is the storage driver that the docker daemon is using. 
The second is the dockerStorageDriverStatus which gives dockers view of the storage pool.
This PR addresses the customer issue rancher/rancher#2023 and rancher/rancher#1586
=> Add better disk reporting for devicemapper setups

cattle/__init__.py, cattle/plugins/cadvisor/cadvisor.py
Look at the docker graph storage area so that cAdvisor will work
when for non-default values.
Addresses issue rancher/rancher#2358
=> Introspect Docker for DockerRootDir for cAdvisor

cattle/plugins/docker/compute.py, cattle/plugins/host_info/main.py, cattle/plugins/host_info/os_c.py, cattle/plugins/host_info/utils.py, tests/docker/ping_resp, tests/docker/ping_stat_exception_resp, tests/test_docker.py, tests/test_host_info_plugin.py
This adds support to the host_info plugin to set labels for host attributes. Currently, Docker version is enabled.
When testing, the label is `io.rancher.host.docker_version: x.x` which will not show up in the UI. It has to be verified via the API.
=> Add support for dynamic host labels

cattle/plugins/host_info/disk.py, tests/test_host_info_plugin.py
With DeviceMapper a pool is created with 100GB pool by default,
without this fix, the UI shows total disk space as Actual + Virtual.
=> Inspect docker pool for device name

cattle/__init__.py, cattle/plugins/cadvisor/cadvisor.py
This PR sets a new housekeeping interval to 5s to reduce
the load cAdvisor puts on a host. It also allows the user to
override that setting by adding CATTLE_CADVISOR_INTERVAL for
users that would like to really reduce its impact can set it to
very high values.
Also added, is a setting for `CATTLE_CADVISOR_OPTS` where users can
add options to the cAdvisor command line. This enables more control
for the user around how cAdvisor behaves. It also opens the door for
adding remote storage and metrics.
This will help with #3017
=> Added new options for configuring cadvisor

cattle/plugins/docker/compute.py, tests/docker/instance_activate_agent_instance_resp, tests/docker/instance_activate_bridge_resp, tests/docker/instance_activate_command_args_resp, tests/docker/instance_activate_command_null_resp, tests/docker/instance_activate_command_resp, tests/docker/instance_activate_double_links_resp, tests/docker/instance_activate_fields_resp, tests/docker/instance_activate_ipsec_lb_agent_resp, tests/docker/instance_activate_ipsec_network_agent_resp, tests/docker/instance_activate_ipsec_resp, tests/docker/instance_activate_labels_resp, tests/docker/instance_activate_links_no_service_resp, tests/docker/instance_activate_links_resp, tests/docker/instance_activate_ports_resp, tests/docker/instance_activate_pull_resp, tests/docker/instance_activate_resp, tests/docker/instance_activate_volumes_resp, tests/docker/instance_deactivate_resp, tests/docker_common.py, tests/test_docker.py
We would ideally like to name containers what the user has specified but
there are concerns right now about /etc/hosts management that Docker
does overriding our DNS based stuff.  We have compromised right now in
naming containers r-{name}.  If we find the name is not unique or the
container name has invalid characters, we fall back to UUID for the
name.
=> Name container as r-{name} and not uuid

cattle/agent/handler.py, cattle/plugins/docker/storage.py, cattle/plugins/docker/util.py
This changed does two things:
1. removes the `-v` ("delete volumes") option from our remove container command so that volume lifecycle can be handle explicitly on its own versus implicity by deleting a container
2. makes the docker storage driver support all volume events instead of just to volume events where the storagepool has a kind of 'docker'. This is because convoy storage pools have a kind of 'storagePool', not  'docker' but python-agent still needs to handle them.
=> Dont delete volumes when deleting container

apply.sh
When overriding the default ca roots, the websocket package
needs to have its pre-packaged cacerts.pem updated.
The conf method sources the agent.conf file if present, before staging/installing the new agent instances.
=> Add prestage of ca roots

apply.sh
This is a bit more defensive, checking for the files in question. It also does not completely replace the cacert.pem with the hosts. Instead it just adds the new CA root to the original pem.
=> Do not replace entire ca file

cattle/plugins/docker/storage.py, cattle/storage/__init__.py, tests/docker_common.py, tests/test_docker.py
This addresses a common problem we've seen in docker 1.10 where
docker's volume ref count becomes inaccurate and docker thinks a volume
is in use by a container when it actually isn't. When this scenario
arises, the volume will get stuck in a purging state in cattle. To
avoid this, we are going to log and ignore 409 errors that arise when
removing a volume.
=> Orphan volume on delete if we get a conflict

requirements.txt, scripts/bootstrap, scripts/build, scripts/ci, scripts/common, scripts/package, scripts/test
The purpose of this PR is to match the version of python that will be added to the rancher/agent image.
Building python 2.7.11 from source and installing it out of the way of the system python. It checks to see if its there on subsequent runs.
Also bumped up requests to match what is running in the Agent image version.
=> Added python 2.7.11 to the build process

cattle/plugins/docker/compute.py, tests/docker/instance_activate_volumes, tests/test_docker.py
@cjellick - This allows passing in mount flags other than `rw` and `ro`
=> allow shared/slave flags for docker volumes

.drone.yml, Dockerfile, cattle/plugins/docker/compute.py, cattle/plugins/host_info/iops.py, cattle/plugins/host_info/main.py, tests/test_docker.py, tests/test_docker_images.py, tests/test_host_info_plugin.py
- Upgrade ci image to 1.10.3 as it is needed to test the blkio fields. This resulted in updating a few tests.
- Add blkio fieds for limiting iops, bps, and weight
- Add an Iops stats collector that will send iops stats up to cattle like we do for disk/memory/cpu/etc
- Add logic to handle a disk of "DEFAULT_DISK" specially. If we see that key, we should attempt to lookup the disk from our iops stats.
=> Add supprt for iops
